name_to_departement = {
    "Benjamin Godard - Victor Hugo": "Unknown",
    "Hôpital Mondor": "Unknown",
    "Toudouze - Clauzel": "Unknown",
    "Cassini - Denfert-Rochereau": "Unknown",
    "Jourdan - Stade Charléty": "Unknown",
    "Basilique": "Unknown",
    "Charonne - Robert et Sonia Delaunay": "Unknown",
    "Messine - Place Du Pérou": "Unknown",
    "Le Brun - Gobelins": "Unknown",
    "Saint-Sulpice": "Unknown",
    "Vaneau - Sèvres": "Unknown",
    "Lacépède - Monge": "Unknown",
    "Saint-Romain - Cherche-Midi": "Unknown",
    "André Karman - République": "Unknown",
    "Pierre et Marie Curie - Maurice Thorez": "Unknown",
    "Bas du Mont-Mesly": "Unknown",
    "Silly - Galliéni": "Unknown",
    "Place Nelson Mandela": "Unknown",
    "Jean Rostand - Paul Vaillant Couturier": "Unknown",
    "Square Boucicaut": "Unknown",
    "Guersant - Gouvion-Saint-Cyr": "Unknown",
    "Thouin - Cardinal Lemoine": "Unknown",
    "Froment - Bréguet": "Unknown",
    "Morillons - Dantzig": "Unknown",
    "Jouffroy d'Abbans - Wagram": "Unknown",
    "Beaux-Arts - Bonaparte": "Unknown",
    "Bracion - Périphérique": "Unknown",
    "Mairie du 12ème": "Unknown",
    "Boétie - Ponthieu": "Unknown",
    "Croulebarde - Corvisart": "Unknown",
    "Le Brix et Mesmin - Jourdan": "Unknown",
    "Romainville - Vaillant-Couturier": "Unknown",
    "Saint-Fiacre - Poissonière": "Unknown",
    "Porte de Saint-Ouen - Bessières": "Unknown",
    "Cambrai - Benjamin Constant": "Unknown",
    "Chazelles - Courcelles ": "Unknown",
    "Moulin de Pierre - Abbé Grégoire": "Unknown",
    "Ramponeau - Belleville": "Unknown",
    "Lagny - Victor Basch": "Unknown",
    "Saint-Cloud - Hippodrome": "Unknown",
    "Louis Lejeune - Barbès": "Unknown",
    "Général Martial Valin - Pont du Garigliano": "Unknown",
    "Rond-point du Dr Albert Schweitzer": "Unknown",
    "Théâtre des Amandiers - Palais des sports": "Unknown",
    "Raspail Barbès": "Unknown",
    "De Toqueville - Terrasse": "Unknown",
    "Jules Guesde - Pont du Port à l'Anglais": "Unknown",
    "8 Mai 1945 - 10 Juillet 1940": "Unknown",
    "Michel-Ange - Parent de Rosan": "Unknown",
    "Caire - Dussoubs": "Unknown",
    "Tour d'Auvergne - Rodier": "Unknown",
    "Artois - Berri": "Unknown",
    "Marceau - Chaillot": "Unknown",
    "Liard - Amiral Mouchez": "Unknown",
    "Regnault - Patay": "Unknown",
    "Vigée-Lebrun - Anselme Payen": "Unknown",
    "Italie - Tolbiac": "Unknown",
    "Félix Ziem - Armand Gauthier": "Unknown",
    "Abbeville - Faubourg Poissonnière": "Unknown",
    "Youri Gagarine - Karl Marx": "Unknown",
    "Octave Feuillet - Albéric Magnard": "Unknown",
    "Place Jean-Spire-Lemaître": "Unknown",
    "Bellefond - Poissonnière": "Unknown",
    "Jean Oestreicher - Porte de Champerret": "Unknown",
    "Square Louis XVI": "Unknown",
    "Granges aux Belles": "Unknown",
    "Dunkerque - Rocroy": "Unknown",
    "Gare de l'Est - Faubourg-Saint-Martin": "Unknown",
    "Gare de Nogent-le-Perreux": "Unknown",
    "Gabriel Lamé": "Unknown",
    "Quai de l'Horloge - Pont Neuf": "Unknown",
    "Boulangers - Cardinal Lemoine": "Unknown",
    "Verger - Colonel Guichard": "Unknown",
    "Gare d'Austerlitz - Quai Saint-Bernard": "Unknown",
    "Pereire - Ternes": "Unknown",
    "Douai - Bruxelles": "Unknown",
    "Gare Saint-Lazare - Isly": "Unknown",
    "Gare Rosny-Bois-Perrier": "Unknown",
    "Porte Pouchet-Bessières": "Unknown",
    "Ségur - d'Estrées": "Unknown",
    "Gay Lussac - Saint-Jacques": "Unknown",
    "Charlot - Stade Gabriel Voisin": "Unknown",
    "Place Georges Guillaumin": "Unknown",
    "Faubourg Montmartre - La Fayette": "Unknown",
    "Boudreau - Auber": "Unknown",
    "Ambroise Rendu - Porte Brunet": "Unknown",
    "Château - République": "Unknown",
    "Henri Barbusse - Stalingrad": "Unknown",
    "Thionville - Ourcq": "Unknown",
    "Rossini - Laffitte": "Unknown",
    "Legendre - Clichy": "Unknown",
    "Quai de la Seine": "Unknown",
    "Argenteuil - Voltaire": "Unknown",
    "Gare de Lyon - Place Louis Armand": "Unknown",
    "Institut du Monde Arabe - Saint-Germain": "Unknown",
    "Pesaro - Préfecture": "Unknown",
    "Ranelagh - Mozart": "Unknown",
    "Moncey - Blanche": "Unknown",
    "Gare du Nord - Hôpital Lariboisière": "Unknown",
    "Redoute - Les Courtilles": "Unknown",
    "Belidor - Gouvion-Saint-Cyr": "Unknown",
    "Place de Rhin et Danube": "Unknown",
    "Exelmans - Versailles": "Unknown",
    "Saint-Maur - Roquette": "Unknown",
    "11 Novembre 1918 - 8 Mai 1945": "Unknown",
    "Roquette - Thiéré": "Unknown",
    "Claude Decaen - Cannebière": "Unknown",
    "Berri - Haussmann": "Unknown",
    "Amelot - Saint-Sébastien": "Unknown",
    "Delphine Seyrig - Général Leclerc": "Unknown",
    "Panthéon - Valette": "Unknown",
    "Chartres - La Charbonnière": "Unknown",
    "Pyrénées - Emmery": "Unknown",
    "Desaix - Edgar Faure": "Unknown",
    "Pereire - Rennequin": "Unknown",
    "Notre-Dame-des-Champs - Stanislas": "Unknown",
    "Saint-Ambroise - Parmentier": "Unknown",
    "Pyramide - Ecole du Breuil ": "Unknown",
    "Liège - Moscou": "Unknown",
    "Mairie de Montreuil": "Unknown",
    "Rouget de Lisle": "Unknown",
    "Récollets - Square Villemin": "Unknown",
    "Place Du Général De Gaulle": "Unknown",
    "Charles de Gaulle - Beauté": "Unknown",
    "Cimetière de Montrouge": "Unknown",
    "Anatole France - President Roosevelt": "Unknown",
    "Henry Farman": "Unknown",
    "Pajol - Place Herbert": "Unknown",
    "Gabriel Péri - Francisco Ferrer": "Unknown",
    "Roger Salengro - Fontainebleau": "Unknown",
    "Marne - Germain Dardan": "Unknown",
    "Concorde - Stalingrad": "Unknown",
    "Carducci - Place Hannah Arendt": "Unknown",
    "Cimetière de Montmartre": "Unknown",
    "Richard Lenoir - Republique": "Unknown",
    "Hôpital Européen Georges Pompidou": "Unknown",
    "Schoelcher - Raspail": "Unknown",
    "Fontenay - Libération": "Unknown",
    "Mutualité": "Unknown",
    "Square Simon Bolivar": "Unknown",
    "Paul Bodin - Clichy": "Unknown",
    "Lobau - Hôtel de Ville": "Unknown",
    "Porte de Vanves": "Unknown",
    "Victor Hugo - Jeanne Jugan": "Unknown",
    "Cimetière de Fontenay-sous-Bois": "Unknown",
    "Lucie Aubrac - Fort": "Unknown",
    "Mouton Duvernet - Général Leclerc": "Unknown",
    "Port-Royal - Hôpital du Val-de-Grâce": "Unknown",
    "Rocher - Laborde": "Unknown",
    "Lecourbe - Jean Maridor": "Unknown",
    "Grenelle - Violet": "Unknown",
    "Erasme - Ulm": "Unknown",
    "Marc Sangnier - Porte de Vanves": "Unknown",
    "Etienne Jodelle - Saint Ouen": "Unknown",
    "Guy Môquet - Etienne Dolet": "Unknown",
    "Boissière - Etienne Dolet": "Unknown",
    "Chabanais - Petits Champs": "Unknown",
    "Marcadet - Barbès": "Unknown",
    "Bertie Albrecht - Hoche": "Unknown",
    "Cevennes - Bergers": "Unknown",
    "Molière - République": "Unknown",
    "Sibelle - Alésia": "Unknown",
    "Hôtel de Ville de Boulogne Billancourt": "Unknown",
    "Enghien - Faubourg Poissonnière": "Unknown",
    "Manin - Carrières d'Amérique": "Unknown",
    "Place de la Porte de Champeret": "Unknown",
    "Place Marcel Cachin": "Unknown",
    "Place de la Reine Astrid": "Unknown",
    "David Weill - Parc Montsouris": "Unknown",
    "Saint Lambert - Blomet": "Unknown",
    "Place Robert Guillemard": "Unknown",
    "Marcelin Berthelot": "Unknown",
    "Edouard Tremblay - Julian Grimaux": "Unknown",
    "Repos - Cimetière du Père Lachaise": "Unknown",
    "Nationale - Place Jules Guesde": "Unknown",
    "Gabriel Péri - Danielle Casanova": "Unknown",
    "Lakanal - Commerce": "Unknown",
    "Censier - Jardin des Plantes": "Unknown",
    "Karl Marx": "Unknown",
    "Tertres - Fontaine": "Unknown",
    "Gare Rer de Fontenay sous Bois": "Unknown",
    "Raspail - Manufacture des Oeillets": "Unknown",
    "Cossonnerie - Sébastopol": "Unknown",
    "Marcelle - Thalie": "Unknown",
    "Cambon - Rivoli": "Unknown",
    "Henri Ste-Claire Déville - Paul Héroult": "Unknown",
    "Louis Lumière - Porte de Bagnolet": "Unknown",
    "Paris - Emile Zola": "Unknown",
    "Jean Jaurès - Salvador Allende": "Unknown",
    "Victoire - Chaussée d'Antin": "Unknown",
    "Assas - Rennes": "Unknown",
    "Oberkampf - République": "Unknown",
    "Richard Lenoir - Jean-Pierre Timbaud": "Unknown",
    "Legendre - Dulong": "Unknown",
    "Chemin Vert - Saint-Maur": "Unknown",
    "Square du Théâtre du Garde-Chasse": "Unknown",
    "Botzaris - Parc des Buttes Chaumont": "Unknown",
    "Général De Gaulle - Alouette": "Unknown",
    "Jules Guesde - Alsace": "Unknown",
    "Joseph Liouville - Croix Nivert": "Unknown",
    "Place Madeleine Daniélou": "Unknown",
    "Rochechouart lamartine": "Unknown",
    "Championnet - Vauvenargues": "Unknown",
    "Jean-François Lépine - Stephenson": "Unknown",
    "Parmentier - République": "Unknown",
    "Sablons - Georges Mandel": "Unknown",
    "Marie-Georges Picquart - Pereire": "Unknown",
    "Gare RER de Vincennes": "Unknown",
    "Théophile Gautier - François Millet": "Unknown",
    "Villette - Belleville": "Unknown",
    "Larmeroux - Baudelaire": "Unknown",
    "Galilée - Kléber": "Unknown",
    "Beffroy": "Unknown",
    "Mairie du 11ème": "Unknown",
    "Marché Secrétan": "Unknown",
    "Quai Panhard et Levassor": "Unknown",
    "Victor Hugo - Galliéni": "Unknown",
    "Lieutenant Chauré - Etienne Marey": "Unknown",
    "Rouget de L'isle - Watteau": "Unknown",
    "Arche - Léonard de Vinci": "Unknown",
    "Charles de Gaulle - Sablonville": "Unknown",
    "Auguste Cain - Jean Moulin": "Unknown",
    "Chemin Vert - Fraternité": "Unknown",
    "Marseille - Beaurepaire": "Unknown",
    "Parmentier - Abel Rabaud": "Unknown",
    "Mairie d'Ivry-sur-Seine": "Unknown",
    "Parc Georges Brassens - Brancion": "Unknown",
    "Place Paul Eluard": "Unknown",
    "Exelmans - Michel-Ange": "Unknown",
    "Pierret - Madrid": "Unknown",
    "Reims - Raymond Pitet": "Unknown",
    "Saint-Vincent - Verdun": "Unknown",
    "Aristide Briand - Gare de Bagneux": "Unknown",
    "Seine - Flandre": "Unknown",
    "Mathurins - Auber": "Unknown",
    "Hautpoul - Jean Jaurès": "Unknown",
    "Wilson - Métallurgie": "Unknown",
    "Madame de Sanzillon - Mozart": "Unknown",
    "Grand Prieuré - Crussol": "Unknown",
    "Leroy des Barres - Médiathèque": "Unknown",
    "Square d'Anvers": "Unknown",
    "Place du Palais Royal": "Unknown",
    "Miromesnil - La Boétie": "Unknown",
    "Mairie du 7ème": "Unknown",
    "Arago - Glacière": "Unknown",
    "Prague - Théophile Roussel": "Unknown",
    "Boyer - Ménilmontant": "Unknown",
    "Laumière - Petit": "Unknown",
    "Gare Arcueil - Cachan": "Unknown",
    "Hôpital Bégin": "Unknown",
    "Gare RER de Gentilly": "Unknown",
    "Quai du docteur Dervaux": "Unknown",
    "Villiers de l'Isle Adam - Pyrénées": "Unknown",
    "Charonne - Avron": "Unknown",
    "Place Jean Ferrat": "Unknown",
    "Place de la Porte de Paris": "Unknown",
    "Place Amédée Gordini - Lefebvre": "Unknown",
    "Stalingrad - Désiré Chevalier": "Unknown",
    "Flandre - Alphonse Karr": "Unknown",
    "Charonne - Faubourg Saint-Antoine": "Unknown",
    "Tristan Tzara -  Tchaïkovski": "Unknown",
    "Hôtel de Ville de Nanterre": "Unknown",
    "Victor Hugo - Ecoles": "Unknown",
    "Général Delambre - Prebuard": "Unknown",
    "Stephenson - Doudeauville": "Unknown",
    "Place de l'Édit de Nantes": "Unknown",
    "Boulard - Daguerre": "Unknown",
    "Charenton - Diderot": "Unknown",
    "Simon Bolivar - Henri Turot": "Unknown",
    "Saint-Germain - Thenard": "Unknown",
    "Jules Ferry - Faubourg du Temple Paris": "Unknown",
    "Saint Georges - d'Aumale": "Unknown",
    "Anatole France - Louise Michel": "Unknown",
    "Montgallet - Charenton": "Unknown",
    "Stalingrad - Germaine Tailleferre": "Unknown",
    "Bienfaisance - Place de Narvik": "Unknown",
    "Guynemer - Séverine": "Unknown",
    "Alfred Roll - Berthier": "Unknown",
    "Richard Wallace - Place du 8 Mai 1945": "Unknown",
    "Square Gilbert Thomain": "Unknown",
    "Faustin Hélie - Desbordes-Valmore": "Unknown",
    "Jean Macé - Faidherbe": "Unknown",
    "Dupleix - du Guesclin": "Unknown",
    "Ancien Canal - Hélène Brion": "Unknown",
    "Departement - Pajol": "Unknown",
    "Flandre - Riquet": "Unknown",
    "Parmentier - Hôpital Saint-Louis": "Unknown",
    "Pasteur - Gambetta": "Unknown",
    "Fragonard - Porte de Clichy": "Unknown",
    "Place des Ternes.": "Unknown",
    "Place de Verdun": "Unknown",
    "Edouard Poisson - Victor Hugo": "Unknown",
    "Montgallet - Reuilly": "Unknown",
    "Montreuil - Gonnet": "Unknown",
    "Varenne": "Unknown",
    "Jussieu - Fossés Saint-Bernard": "Unknown",
    "Jacques Callot - Mazarine": "Unknown",
    "Porte de Vincennes": "Unknown",
    "Place Jacques Madaule": "Unknown",
    "Commandant Rivière": "Unknown",
    "Jardin d'Acclimatation": "Unknown",
    "Paul Vaillant Couturier - Chaptal": "Unknown",
    "Square Cambronne": "Unknown",
    "Gare de Laplace": "Unknown",
    "Bayen - Pereire": "Unknown",
    "Clignancourt - Sofia": "Unknown",
    "Route de Sèvres - Porte de Bagatelle": "Unknown",
    "Bordier - Félix Faure": "Unknown",
    "Félix Faure - Sadi Carnot": "Unknown",
    "Cujas - Saint-Michel": "Unknown",
    "18 juin 1940 - Buzenval": "Unknown",
    "Mairie de La Garenne Colombes": "Unknown",
    "Jean Colly - Tolbiac": "Unknown",
    "Porte de la Villette": "Unknown",
    "Ouest - Château ": "Unknown",
    "Place aux Étoiles": "Unknown",
    "Flandrin - Henri Martin": "Unknown",
    "Pirogues de Bercy - Libourne": "Unknown",
    "Place Violet": "Unknown",
    "Place du 8 Mai 1945": "Unknown",
    "Grands Moulins de Pantin": "Unknown",
    "Gare de Courbevoie": "Unknown",
    "Victor Hugo - Magasins Généraux": "Unknown",
    "Porte d'Auteuil": "Unknown",
    "Carnot - Pâquerettes": "Unknown",
    "Assemblée Nationale": "Unknown",
    "Réunion - Avron": "Unknown",
    "Place Jean-Baptiste Clément": "Unknown",
    "Chanzy - Sud-Est": "Unknown",
    "Jussieu - Guy de la Brosse": "Unknown",
    "Jean Lolive - Parc Stalingrad": "Unknown",
    "Courcelles - Place des Ternes": "Unknown",
    "Parc Pierre Lagravère": "Unknown",
    "Guichet - Jean Jaurès": "Unknown",
    "Parvis Robert Schuman - Roger Salengro": "Unknown",
    "Navier - Epinettes": "Unknown",
    "Verdun - Place Henri IV": "Unknown",
    "Place Carnot": "Unknown",
    "Gare de Bercy": "Unknown",
    "Ceinture du Lac Inferieure - Saint-Cloud": "Unknown",
    "Anatole France - Jean Lolive": "Unknown",
    "Boyer-Barret - Raymond Losserand": "Unknown",
    "Piat - Parc de Belleville": "Unknown",
    "Square des Saint-Simoniens": "Unknown",
    "Champeaux - Gallieni": "Unknown",
    "Assas - Vaugirard": "Unknown",
    "Raymond Poincaré - Allée de la Marche": "Unknown",
    "Gravelle - Route du Bac": "Unknown",
    "Ménilmontant - Pelleport": "Unknown",
    "Petit - Manin": "Unknown",
    "Lagny - Joffre": "Unknown",
    "Place Falguière": "Unknown",
    "Emeriau - Place de Brazzaville": "Unknown",
    "Parc Monceau": "Unknown",
    "Tardieu - Chappe": "Unknown",
    "Petites Ecuries - Faubourg Poissonnière": "Unknown",
    "Nanterre - Université": "Unknown",
    "Gare d'Asnières sur Seine": "Unknown",
    "Francoeur - Marcadet": "Unknown",
    "Henri Chevreau - Couronnes": "Unknown",
    "Pascal - Claude Bernard": "Unknown",
    "Vignerons - Minimes": "Unknown",
    "Sommerard - Saint-Jacques": "Unknown",
    "Grenelle - Dr Finlay": "Unknown",
    "Lamennais - Washington ": "Unknown",
    "Porte d'Orléans": "Unknown",
    "Pierre et Marie Curie - Julien Grimau": "Unknown",
    "Raspail - Varenne": "Unknown",
    "Pierre Grenier - Pont de Billancourt": "Unknown",
    "Vladimir Ilitch Lénine - Andrée Chedid": "Unknown",
    "Professeur René Leriche - Général Leclerc ": "Unknown",
    "Uzès - Montmartre": "Unknown",
    "Ledru-Rollin - Charonne": "Unknown",
    "Place Valhubert": "Unknown",
    "Quai Voltaire": "Unknown",
    "Saint-François-Xavier": "Unknown",
    "Batignolles - Place de Clichy": "Unknown",
    "Parc de Belleville - Julien Lacroix": "Unknown",
    "Gare de Pont-Cardinet": "Unknown",
    "Gare de l'Est - Verdun": "Unknown",
    "Capitaine Glarner - Gabriel Péri": "Unknown",
    "Place Jean Delay": "Unknown",
    "Pont de Levallois-bécon ": "Unknown",
    "Pierre Larousse - Raymond Losserand": "Unknown",
    "Pitié-Salpêtrière": "Unknown",
    "Charles Delescluze": "Unknown",
    "Vasco de Gama": "Unknown",
    "Jonquoy - Didot": "Unknown",
    "Lucien Sampaix - Récollets": "Unknown",
    "Place du Général de Gaulle": "Unknown",
    "Charenton - Place du Col Bourgoin": "Unknown",
    "Bara - Henri Farman": "Unknown",
    "Porte Dorée": "Unknown",
    "Belleville - Porte des Lilas": "Unknown",
    "Mézières - Rennes ": "Unknown",
    "Place Adolphe Cherioux - Vaugirard": "Unknown",
    "Sèvres-Gallieni": "Unknown",
    "Indre - Prairies": "Unknown",
    "Raspail - Bac": "Unknown",
    "Michelet - Assas": "Unknown",
    "Edouard Vaillant - Paul-Adolphe Souriau": "Unknown",
    "Morice - Général Leclerc": "Unknown",
    "Tanger - Place du Maroc": "Unknown",
    "Vincennes - Douy-Delcupe": "Unknown",
    "Place du Cornillon - Stade de France": "Unknown",
    "Porte de Clignancourt.": "Unknown",
    "Porte de Saint-Ouen - Henri Huchard": "Unknown",
    "Génie - Mozart": "Unknown",
    "Place du Maréchal Juin - Péreire": "Unknown",
    "Lucie Aubrac - Franklin": "Unknown",
    "Hôtel de Ville d'Argenteuil": "Unknown",
    "Gare Routière de Saint Cloud": "Unknown",
    "Primo Levi - Frigos": "Unknown",
    "Dunois - Clisson": "Unknown",
    "Batignolles - Rome": "Unknown",
    "Filles Saint-Thomas - Place de la Bourse": "Unknown",
    "Verdun - Adrien Damalix": "Unknown",
    "Milton - Manuel": "Unknown",
    "Edouard Pailleron - Simon Bolivar ": "Unknown",
    "Eglise d'Auteuil": "Unknown",
    "Jean Jaurès - Jean Baptiste Clément ": "Unknown",
    "Château - Bineau": "Unknown",
    "Mairie du 18ème": "Unknown",
    "Bridaine - Lamandé": "Unknown",
    "Porte de Ménilmontant": "Unknown",
    "Laffitte - Italiens": "Unknown",
    "Colonel Monteil - Brune": "Unknown",
    "Mahatma Gandhi": "Unknown",
    "Paris - Désiré Préaux": "Unknown",
    "Lourmel - Marie Skobtsov": "Unknown",
    "Belleville - Télégraphe": "Unknown",
    "Courcelles - Pierre Demours": "Unknown",
    "Danton - Serpente": "Unknown",
    "République - Danton": "Unknown",
    "Mac-Mahon - Brey": "Unknown",
    "Square des Epinettes": "Unknown",
    "Cité des Sciences et de l'Industrie": "Unknown",
    "Pajol - Riquet ": "Unknown",
    "Lassus - Delouvain": "Unknown",
    "Emile Blemont - Poteau": "Unknown",
    "Square du Carrefour de l'Insurrection": "Unknown",
    "Toffier Decaux - Cartier Bresson": "Unknown",
    "Orteaux - Mouraud": "Unknown",
    "François Ponsard - La Muette ": "Unknown",
    "Provence - Chaussée d'Antin": "Unknown",
    "Bellefond - Maubeuge": "Unknown",
    "Pelleport - Belgrand": "Unknown",
    "Edgar Quinet - Raspail": "Unknown",
    "Place Etienne Pernet": "Unknown",
    "Porte d'Aubervilliers": "Unknown",
    "Chabrol - d'Hauteville": "Unknown",
    "Lepic - Armée d'Orient": "Unknown",
    "Hôtel de Ville de Saint-Ouen": "Unknown",
    "Square Saint-Ambroise": "Unknown",
    "Sadi Carnot - François Mitterrand ": "Unknown",
    "Gabrielle Josserand - Edouard Vaillant": "Unknown",
    "Théâtre - Lourmel": "Unknown",
    "Hameau Fleuri - Marché": "Unknown",
    "Square René Viviani - Montebello": "Unknown",
    "Ledru-Rollin - Place du Père Chaillet": "Unknown",
    "Ecole Vétérinaire": "Unknown",
    "Aubervilliers - Curial": "Unknown",
    "Bassano -  Iéna": "Unknown",
    "Lavandieres Sainte Opportune - Rivoli": "Unknown",
    "Méchain - Faubourg Saint-Jacques": "Unknown",
    "Stade Auguste Delaune": "Unknown",
    "Jean-Baptiste Pigalle - La Bruyere": "Unknown",
    "Transvaal - Charles de Gaulle ": "Unknown",
    "Belliard - Damrémont": "Unknown",
    "Boulets - Faubourg Saint-Antoine": "Unknown",
    "Route de la Muette - Porte de Neuilly": "Unknown",
    "Maine - Antoine Bourdelle": "Unknown",
    "Kléber - Gouverneur Général Eboué": "Unknown",
    "Président Wilson - Jean Jaures": "Unknown",
    "Pyrénées - Maraîchers": "Unknown",
    "Gare RER de Saint-Denis": "Unknown",
    "Place Jacques Bonsergent": "Unknown",
    "Place de Passy": "Unknown",
    "Mozart - Jasmin": "Unknown",
    "Haies - Réunion": "Unknown",
    "Place Alphonse Deville": "Unknown",
    "Maison de Radio - France": "Unknown",
    "Naples - Rome": "Unknown",
    "Lallier - Trudaine ": "Unknown",
    "Square Léon": "Unknown",
    "Villersexel - Saint-Germain": "Unknown",
    "Chernoviz - Raynouard": "Unknown",
    "Fontainebleau - Edmond Michelet": "Unknown",
    "Pernety - Raymond Losserand": "Unknown",
    "Eugène Reisz - Davout": "Unknown",
    "Eugène Oudiné - Dessous Des Berges": "Unknown",
    "Mont Valérien - Michel Salles": "Unknown",
    "Gare Montparnasse - Vaugirard": "Unknown",
    "Neuve Saint-Pierre - Beautreillis": "Unknown",
    "Sabot - Rennes": "Unknown",
    "Pereire - Place de Wagram": "Unknown",
    "Champ de Mars - Cler": "Unknown",
    "Aqueduc - Villette": "Unknown",
    "Mairie de Sceaux": "Unknown",
    "Sénat - Condé": "Unknown",
    "Diderot - Reuilly": "Unknown",
    "Palais des Sports": "Unknown",
    "Cadet - La Fayette": "Unknown",
    "Caulaincourt - Place Constantin Pecqueur": "Unknown",
    "Belleville - Pyrénées": "Unknown",
    "Place Pasdeloup": "Unknown",
    "Pont Neuf - Rivoli": "Unknown",
    "Hôpital Pitié Salpêtrière": "Unknown",
    "Parc André Citroën": "Unknown",
    "Place d'Italie - Vincent Auriol": "Unknown",
    "Stade Gaston Bouillant": "Unknown",
    "Jeanne Hornet - Girardot": "Unknown",
    "Calmette": "Unknown",
    "Porte Maillot - Perreire": "Unknown",
    "Chateau": "Unknown",
    "Vieille du Temple - Francs Bourgeois": "Unknown",
    "Hôtel de Ville de Champigny sur Marne": "Unknown",
    "Place François Mitterand": "Unknown",
    "Faubourg Poissonniere - Delta": "Unknown",
    "Billancourt - Général Leclerc ": "Unknown",
    "Gare du Nord - Demarquay": "Unknown",
    "Greneta - Sebastopol": "Unknown",
    "Manin - Simon Bolivar": "Unknown",
    "Place du Maquis du Vercors": "Unknown",
    "Poissonniers - Nord": "Unknown",
    "Raspail - Chomel": "Unknown",
    "Reims - Porte d'Asnières": "Unknown",
    "Station Paris Basketball - Ney - Charles Hermite": "Unknown",
    "Porte d'Ivry": "Unknown",
    "Surcouf - Université": "Unknown",
    "Hôtel de Ville - Pont-Marie": "Unknown",
    "Bois de Vincennes.": "Unknown",
    "Bercy.": "Unknown",
    "Saint-Jacques - Tombe Issoire": "Unknown",
    "Duroc - Place de Breteuil": "Unknown",
    "Beaujon - Wagram": "Unknown",
    "Parvis Corentin Celton": "Unknown",
    "Gustave Eiffel - Parc des Impressionnistes": "Unknown",
    "Centenaire - Sorins": "Unknown",
    "Franciade - Gabriel Péri": "Unknown",
    "Brochant - Square des Batignolles ": "Unknown",
    "Dupont de l'Eure - Gambetta": "Unknown",
    "Square Raymond Souplex": "Unknown",
    "Keller - La Roquette": "Unknown",
    "Parmentier - Fontaine au Roi": "Unknown",
    "Rougemont - Poissonnière": "Unknown",
    "Mairie du 15ème": "Unknown",
    "Place des Larris": "Unknown",
    "Vistule - Choisy": "Unknown",
    "Manin - Crimée": "Unknown",
    "Nationale - Marcel Duchamp": "Unknown",
    "Square Desnouettes": "Unknown",
    "Saint-Blaise - Mouraud": "Unknown",
    "Charonne - Philippe-Auguste": "Unknown",
    "Hôtel de Ville de Levallois Perret": "Unknown",
    "Mairie de Clichy": "Unknown",
    "Pont de Lodi - Dauphine": "Unknown",
    "Romain Rolland": "Unknown",
    "Gambetta - Michelet": "Unknown",
    "Les Juilliottes": "Unknown",
    "République - Henri Barbusse": "Unknown",
    "Jeûneurs - Mulhouse": "Unknown",
    "Place de Finlande": "Unknown",
    "Thérèse - Opéra": "Unknown",
    "Roquépine - Malesherbes": "Unknown",
    "Poissy - Saint-Germain": "Unknown",
    "Ferrus - Saint-Jacques": "Unknown",
    "Claude Vellefaux - Sambre et Meuse": "Unknown",
    "Faidherbe - Dahomey": "Unknown",
    "Bleue - Trévise": "Unknown",
    "Le Vau - Maurice Bertaux": "Unknown",
    "Daunou - Louis le Grand": "Unknown",
    "Mornay - Sully": "Unknown",
    "Porte Saint-Martin": "Unknown",
    "Georges V - François 1er": "Unknown",
    "Place Mireille Havet": "Unknown",
    "Bachaumont - Montmartre": "Unknown",
    "Square Georges Melies": "Unknown",
    "Charles de Gaulle - Louis Philippe": "Unknown",
    "Mairie du 19ème": "Unknown",
    "Jardin Marguerite Long": "Unknown",
    "Melun - Jean Jaurès": "Unknown",
    "Jean Jaurès - Reine": "Unknown",
    "Argenson - Château": "Unknown",
    "Place de l'Eglise - Pantin": "Unknown",
    "Butte aux Cailles - Esperance": "Unknown",
    "Louis Ganne - Davout": "Unknown",
    "Fernand Braudel - Vincent Auriol ": "Unknown",
    "Square du Bataclan": "Unknown",
    "Sorbonne - Ecoles": "Unknown",
    "Versailles - Claude Terrasse": "Unknown",
    "Place Tony de Graaff": "Unknown",
    "Lamartine - Faubourg Montmartre": "Unknown",
    "Place du Canada": "Unknown",
    "François 1er - Lincoln": "Unknown",
    "Carnot - Général Lanrezac": "Unknown",
    "Roquette - Folie Regnault": "Unknown",
    "Vignes - Boulainvilliers": "Unknown",
    "Terroirs de France - Lheureux": "Unknown",
    "Brochant - Clichy": "Unknown",
    "Place Marcel Sembat": "Unknown",
    "Odessa - Départ": "Unknown",
    "René Coty - Parc Montsouris": "Unknown",
    "François Truffaut - Saint Emilion": "Unknown",
    "Madeleine Michelis - Roule": "Unknown",
    "Jessaint - Marx Dormoy": "Unknown",
    "Lac Daumesnil - Saint-Maurice": "Unknown",
    "René Binet - Porte de Montmartre": "Unknown",
    "Moulin de la Pointe": "Unknown",
    "Sèvres Rive Gauche": "Unknown",
    "Suffren - Pérignon": "Unknown",
    "Gare de Clichy-Levallois ": "Unknown",
    "Docteur Calmette - Martre": "Unknown",
    "Saint-Fargeau - Mortier": "Unknown",
    "République - Auguste Perret": "Unknown",
    "Dareau - Broussais": "Unknown",
    "Le Corbusier - Jean Jaurès": "Unknown",
    "Jean Moulin - Paul Doumer": "Unknown",
    "Boutroux - Porte de Vitry": "Unknown",
    "Véron - Lepic": "Unknown",
    "Pont De Charenton": "Unknown",
    "Beaumarchais - Pas de la Mule": "Unknown",
    "Pierre Brossolette - Adolphe Pinard": "Unknown",
    "Quai Marcel Boyer - Victor Hugo": "Unknown",
    "Cours de Vincennes - Davout": "Unknown",
    "Mairie du 9ème": "Unknown",
    "Place Centrale": "Unknown",
    "Gare de Nanterre Ville": "Unknown",
    "Senard - Charles Blum": "Unknown",
    "Pré Saint-Gervais - Lilas": "Unknown",
    "Gergovie - Vercingétorix": "Unknown",
    "Sambre et Meuse - Villette": "Unknown",
    "Hôpital Robert Debré": "Unknown",
    "Jules Guesde - Laennec": "Unknown",
    "Demi-Lune - Aristide Briand": "Unknown",
    "Guy Môquet - Saint-Ouen": "Unknown",
    "Bois de Vincennes - Porte Jaune": "Unknown",
    "Place du Président Salvador Allende": "Unknown",
    "Edouard Vaillant - Galliéni": "Unknown",
    "Clapeyron - Moscou": "Unknown",
    "Paul Klee - Place Augusta Holmes": "Unknown",
    "Alexander Fleming - Belvédère": "Unknown",
    "Constantine - Université": "Unknown",
    "Santé - Arago": "Unknown",
    "Averroès - Aimé Césaire": "Unknown",
    "Place du Front Populaire - George Sand": "Unknown",
    "Paul Barruel - Vaugirard": "Unknown",
    "Evariste Galois": "Unknown",
    "Rapp - Place du Général Gouraud": "Unknown",
    "Commandant l'Herminier - Gallieni": "Unknown",
    "Bastille - Quai de la Rapée": "Unknown",
    "Jacquard - Ternaux": "Unknown",
    "Pyramide - Parc Floral": "Unknown",
    "Auguste Blanqui - Glacière": "Unknown",
    "Choron - Martyrs": "Unknown",
    "Gare du Nord - Place de Valenciennes": "Unknown",
    "Charles Lecocq - Lecourbe": "Unknown",
    "Quai de Valmy": "Unknown",
    "Athènes - Clichy": "Unknown",
    "Parc Suzanne Lenglen": "Unknown",
    "Stade Georges Carpentier": "Unknown",
    "Mazagran - Pierre de Coubertin": "Unknown",
    "Pierre Demours - Laugier": "Unknown",
    "Metz - Faubourg Saint-Denis": "Unknown",
    "Neuilly - Petit": "Unknown",
    "Pelée - Alphonse Baudin": "Unknown",
    "Belleville - Couronnes": "Unknown",
    "Place Jules Ferry": "Unknown",
    "Censier - Santeuil": "Unknown",
    "Gare de l'Est - Fidélité": "Unknown",
    "Cimetière d'Issy-les-Moulineaux": "Unknown",
    "Botzaris - Crimée": "Unknown",
    "Saint-Didier - Raymond Poincaré": "Unknown",
    "Cours de l'Ile Seguin - Parc Billancourt": "Unknown",
    "Gare du Nord - Denain": "Unknown",
    "André Maurois - Joseph et Marie Hackin": "Unknown",
    "Place Fernand Forest": "Unknown",
    "Gare de Lyon - Van Gogh": "Unknown",
    "Eylau - Trocadéro": "Unknown",
    "Longchamp - Place d'Iéna": "Unknown",
    "Mairie de Neuilly sur Seine": "Unknown",
    "Louis Blanc - Jemmapes": "Unknown",
    "Chancé Milly - Cimetière Communal Sud": "Unknown",
    "Marcel Yol - Jullien": "Unknown",
    "Victor Cresson - Telles de la Poterie": "Unknown",
    "Hôtel de ville de Fontenay-sous-Bois": "Unknown",
    "Gare SNCF Vanves-Malakoff": "Unknown",
    "Marc Sangnier - Division Leclerc": "Unknown",
    "Pierre Levée - Fontaine Timbaud": "Unknown",
    "Convention - Vaugirard": "Unknown",
    "Résistance - Hoche": "Unknown",
    "Paul Vaillant-Couturier - Gare RER": "Unknown",
    "Raffet - Montmorency": "Unknown",
    "Commerce - Letellier": "Unknown",
    "Ivry - Simone Weil": "Unknown",
    "Fessart - Château": "Unknown",
    "Cimetière de Boulogne-Billancourt": "Unknown",
    "Ranelagh - Maison de la Radio": "Unknown",
    "Brancion - Lefebvre": "Unknown",
    "Place Saint-Ferdinand": "Unknown",
    "Hôtel de Ville de Fontenay-aux-Roses": "Unknown",
    "Docteurs Déjérine - Pte de Montreuil": "Unknown",
    "Vanne - Saussaies": "Unknown",
    "Jean-Pierre Timbaud - Vaucouleurs": "Unknown",
    "Vaugirard - Verrerie": "Unknown",
    "Malakoff - Place de la Porte Maillot": "Unknown",
    "Bruneseau - Quai d'Ivry": "Unknown",
    "Petit Palais": "Unknown",
    "Vinaigriers - Magenta": "Unknown",
    "Wurtz - Tolbiac": "Unknown",
    "Pierre Lefaucheux - Traversière": "Unknown",
    "Quai aux Fleurs - Pont Saint-Louis": "Unknown",
    "Square Alban Satragne": "Unknown",
    "Mairie de Romainville": "Unknown",
    "Jardin de l'Hospice Debrousse": "Unknown",
    "Amaury Duval - Gabriel Péri": "Unknown",
    "Arcole - Notre-Dame": "Unknown",
    "Paul Signac - Aristide Briand": "Unknown",
    "Jean Calvin - Tournefort": "Unknown",
    "Gallieni - Lycée Charles Petitet": "Unknown",
    "Buzenval - Avron": "Unknown",
    "Porte d'Italie": "Unknown",
    "Charles Gide - Fort de Bicêtre ": "Unknown",
    "Vitruve - Davout": "Unknown",
    "Place de la Porte de Passy": "Unknown",
    "Place Nationale - Château-des-Rentiers": "Unknown",
    "Gare Montparnasse - Edgar Quinet": "Unknown",
    "Batignolles - Beudant": "Unknown",
    "Place de Lévis": "Unknown",
    "La Motte-Picquet - Grenelle": "Unknown",
    "Théâtre de La Garenne": "Unknown",
    "Place de l'Insurrection d'Août 1944 ": "Unknown",
    "Hôpital - Campo-Formio": "Unknown",
    "Lycée Saint Exupéry - Juliette Savar": "Unknown",
    "Daumesnil - Hébrard": "Unknown",
    "George V - Christophe Colomb": "Unknown",
    "Président Wilson - Baudin": "Unknown",
    "Jourdan - Monticelli": "Unknown",
    "Porte d'Asnières": "Unknown",
    "Gaston Tessier - Rosa Parks RER": "Unknown",
    "Camille Groult - Guy Môquet": "Unknown",
    "Marché aux fleurs": "Unknown",
    "Mazagran - Bonne Nouvelle": "Unknown",
    "Jacques Kellner - Saint-Ouen": "Unknown",
    "Raspail - Albert Schweitzer": "Unknown",
    "Assas - Luxembourg": "Unknown",
    "Brillat-Savarin - Küss": "Unknown",
    "Estienne d'Orves - Henri Ginoux": "Unknown",
    "Place de l'Europe - Quai de Bercy": "Unknown",
    "Louis Pasteur - Albert Petit": "Unknown",
    "Charonne - Pierre Bayle": "Unknown",
    "Louis Rolland - République": "Unknown",
    "Emeriau - Beaugrenelle": "Unknown",
    "Faubourg Poissonnière - Dunkerque": "Unknown",
    "Victor Hugo - La Pompe": "Unknown",
    "Gare de Lyon - Chalon": "Unknown",
    "Colmar - Victor Hugo": "Unknown",
    "Benjamin Delessert - Jean Lolive": "Unknown",
    "Place de la Gare": "Unknown",
    "Place Mongolfier": "Unknown",
    "Italie - Jardin Joan Miro": "Unknown",
    "Gare de l'Est - Place du 11 Novembre 1918": "Unknown",
    "Javel - André Citroën": "Unknown",
    "Jean Moulin - Place Victor et Hélène Basch": "Unknown",
    "Paris - Laitières": "Unknown",
    "Quai de la Gare - Pont de Bercy": "Unknown",
    "Lucien Lanternier - Le Luth": "Unknown",
    "Mairie de quartier du Plateau - Mont-Valérien": "Unknown",
    "La Jarry - Place Diderot": "Unknown",
    "Berthier - Place Stuart Merril": "Unknown",
    "Lucien Bossoutrot - Général Martial Vallin": "Unknown",
    "Pergolèse - Malakoff": "Unknown",
    "Vaugirard - Pasteur": "Unknown",
    "Voltaire - Anatole France": "Unknown",
    "Blaise-Desgoffe - Vaugirard": "Unknown",
    "Goutte d'or - Barbès": "Unknown",
    "Quai de l'Oise - Aisne": "Unknown",
    "Place Jacques et Thérèse Tréfouël": "Unknown",
    "Square Louise Michel": "Unknown",
    "Mairie de Clamart": "Unknown",
    "Place Jeanne d'Arc": "Unknown",
    "Douai - Pierre Fontaine": "Unknown",
    "Bessières - Porte de Clichy": "Unknown",
    "Place Edmond Michelet": "Unknown",
    "Emile Zola - Fondary": "Unknown",
    "Paul Vaillant-Couturier - Victor Hugo": "Unknown",
    "Place du 14 Juillet": "Unknown",
    "Estrapade - Ulm": "Unknown",
    "Monceau - Malesherbes": "Unknown",
    "Charonne - Bureau": "Unknown",
    "Place Lafayette": "Unknown",
    "Halles - Bourdonnais": "Unknown",
    "Charles Tillon - Cimetière Communal": "Unknown",
    "La Motte-Picquet - La Tour Maubourg": "Unknown",
    "Quai du Président Roosevelt - Pont Aval": "Unknown",
    "Delizy - Louis Nadot": "Unknown",
    "Maréchal Joffre - Verdun": "Unknown",
    "Île de la Jatte": "Unknown",
    "Saint-Mandé - Fabre d'Eglantine": "Unknown",
    "Place Saint-Just": "Unknown",
    "Toqueville - Cardinet": "Unknown",
    "Cambronne - Villa Croix Nivert": "Unknown",
    "Gérando - Rochechouart": "Unknown",
    "Placette Grégoire Collas": "Unknown",
    "Porte des Lilas - Faidherbe": "Unknown",
    "Fort d'Aubervilliers": "Unknown",
    "Place Ginette Hamelin": "Unknown",
    "Alexandre Parodi - Quai de Valmy": "Unknown",
    "Saint-Germain - Ciseaux": "Unknown",
    "Auguste Blanqui - Corvisart": "Unknown",
    "Gare du Stade": "Unknown",
    "Balzac - Olympes de Gouges": "Unknown",
    "Suffren - Champ de Mars": "Unknown",
    "Taitbout - La Fayette": "Unknown",
    "Arsène Houssaye - Friedland": "Unknown",
    "Lemercier - Cardinet": "Unknown",
    "Esplanade du Foncet - Camille Desmoulins": "Unknown",
    "Londres - Place d'Estienne d'Orves": "Unknown",
    "Dunkerque - Trudaine": "Unknown",
    "Champs-Elysees - Bassano": "Unknown",
    "Joseph Dijon - Ornano": "Unknown",
    "Place Monge": "Unknown",
    "Square Denise Buisson": "Unknown",
    "Chemin de Bretagne": "Unknown",
    "Picpus - Louis Braille": "Unknown",
    "Crozatier - Faubourg Saint-Antoine": "Unknown",
    "Glacière - Soeur Catherine Marie": "Unknown",
    "Rottembourg - Général Michel Bizot": "Unknown",
    "Geoffroy - Marie": "Unknown",
    "Vivaldi - Antoine-Julien Hénard": "Unknown",
    "Godot de Mauroy - Madeleine": "Unknown",
    "Madagascar - Meuniers": "Unknown",
    "Marché Saint-Quentin": "Unknown",
    "Buffon - Jardin des Plantes": "Unknown",
    "Louis Xavier de Ricard - Ancienne Mairie": "Unknown",
    "Lebrun - Colonel Fabien ": "Unknown",
    "Vivienne - Montmartre": "Unknown",
    "Charenton - Prague": "Unknown",
    "Square Etienne Jarousse": "Unknown",
    "Cloître Saint-Merri - Renard": "Unknown",
    "Harpe - Saint-Germain": "Unknown",
    "Hôpital Necker": "Unknown",
    "Bourg l'Abbé - Saint-Martin": "Unknown",
    "Gare d'Argenteuil": "Unknown",
    "Mairie du 8ème ": "Unknown",
    "Abbé Groult - Convention": "Unknown",
    "Jules Guesdes - Général de Gaulle": "Unknown",
    "Hôtel de Ville de Sèvres": "Unknown",
    "Marché Saint-Germain": "Unknown",
    "Cherche-Midi - Hôpital Necker": "Unknown",
    "Place Aimé Césaire": "Unknown",
    "Leredde - Tolbiac": "Unknown",
    "Gare RER - Malleret-Joinville": "Unknown",
    "Bruant - Vincent Auriol": "Unknown",
    "Jean Monnet - Iles": "Unknown",
    "Parc Eli Lotar": "Unknown",
    "Condorcet - Turgot": "Unknown",
    "Villiers - Batignolles": "Unknown",
    "Place Charles Michels": "Unknown",
    "Benoît Frachon - République": "Unknown",
    "Jean Jaurès - Jules Jacquemin": "Unknown",
    "Mairie du 14ème": "Unknown",
    "Place des Droits de l'Enfant": "Unknown",
    "Marne - Charles de Gaulle": "Unknown",
    "Saint-Benoît - Jacob": "Unknown",
    "Didot - Place de Moro-Giafferi": "Unknown",
    "Davout - Volga": "Unknown",
    "Porte de la Muette": "Unknown",
    "Landy - Heurtault": "Unknown",
    "Favart - Italiens": "Unknown",
    "Balard - Montagne de la Fage": "Unknown",
    "Paradis - Hauteville": "Unknown",
    "Bréguet - Sabin": "Unknown",
    "Stalingrad - Rigollots": "Unknown",
    "Gare du Nord - Saint-Vincent de Paul": "Unknown",
    "Jardins d'Eole": "Unknown",
    "Porte de Bagnolet": "Unknown",
    "Reuilly - Place Felix Eboue": "Unknown",
    "Plantes - Moulin Vert": "Unknown",
    "Cité Riverin - Château d'Eau": "Unknown",
    "Flandrin - Longchamp": "Unknown",
    "Porte Molitor": "Unknown",
    "Charles Frérot - Albert Guilpin": "Unknown",
    "Place de la Madeleine - Royale": "Unknown",
    "Claude Vellefaux - Hôpital Saint-Louis": "Unknown",
    "Place de la Nation - Picpus": "Unknown",
    "Maxime Gorki - Louis Aragon": "Unknown",
    "Edgar Quinet - Gaité": "Unknown",
    "Gare RER les Grésillons": "Unknown",
    "Poissonniers - Championnet": "Unknown",
    "Murat - Porte de Saint-Cloud": "Unknown",
    "Grande Truanderie - Saint-Denis": "Unknown",
    "Gare Montparnasse - Arrivée": "Unknown",
    "Sèvres - Lecourbe": "Unknown",
    "Square Claude Bernard": "Unknown",
    "Henri Ravera - Gabriel Péri": "Unknown",
    "Jules Vallès - Charonne": "Unknown",
    "Ecoles - Carmes": "Unknown",
    "Crevaux - Bugeaud": "Unknown",
    "Bourdon - Pont Morland": "Unknown",
    "Diane Arbus": "Unknown",
    "Perle - Vieille du Temple": "Unknown",
    "Chevreuse - Montparnasse": "Unknown",
    "Epée de Bois - Mouffetard": "Unknown",
    "Roger Salengro - Général de Gaulle": "Unknown",
    "Cadix - Hameau": "Unknown",
    "Camille Risch - Paul Armangot": "Unknown",
    "Reuilly - Daumesnil": "Unknown",
    "Turbigo - Française": "Unknown",
    "Mairie d'Issy": "Unknown",
    "Charentonneau - Maisons Alfort": "Unknown",
    "Place des Abbesses": "Unknown",
    "Mairie du 16ème": "Unknown",
    "Cité Vaneau": "Unknown",
    "Pyrénées - Avron": "Unknown",
    "Leibniz - Jean Dollfus": "Unknown",
    "Gare de Reuilly - Picpus": "Unknown",
    "Louis Lumière.": "Unknown",
    "Jourdan - Cité Universitaire": "Unknown",
    "Gare Saint-Lazare - Stockholm": "Unknown",
    "Gambetta - Père Lachaise": "Unknown",
    "Beaubourg - Michel-le-Comte": "Unknown",
    "Niger - Soult": "Unknown",
    "Porte de Clignancourt - Ney": "Unknown",
    "Centquatre": "Unknown",
    "Square Montholon": "Unknown",
    "Louis Blanc - La Chapelle": "Unknown",
    "Herschel - Observatoire": "Unknown",
    "Pergolèse - Marbeau": "Unknown",
    "Centre Georges Pompidou": "Unknown",
    "Sorbier - Ménilmontant": "Unknown",
    "Cordelières - Arago": "Unknown",
    "Place de la Nation - Charonne": "Unknown",
    "Phalsbourg - Villiers": "Unknown",
    "Petit - Georges Thill": "Unknown",
    "Emile Reynaud - Porte de la Villette ": "Unknown",
    "Chausson - Gabriel Péri": "Unknown",
    "Bargue -  Dutot": "Unknown",
    "Place de l'Europe - Alfortville": "Unknown",
    "Pyrénées - Plaine": "Unknown",
    "Arsène Houssaye - Champs-Elysées": "Unknown",
    "Bourse du Travail": "Unknown",
    "Gare de Bellevue": "Unknown",
    "Maurice d'Ocagne - General Maudhuy": "Unknown",
    "Sarrette - Général Leclerc": "Unknown",
    "Turbigo - Réaumur": "Unknown",
    "Place de la Fraternité": "Unknown",
    "Dunkerque - Alsace": "Unknown",
    "Petites Ecuries - Faubourg Saint-Denis": "Unknown",
    "Charles de Gaulle - Plateau de Vanves": "Unknown",
    "Lacuée - Lyon": "Unknown",
    "Maurice Payret-Dortail": "Unknown",
    "Archives - Rivoli": "Unknown",
    "Maine - Liancourt": "Unknown",
    "Beaumarchais - Saint-Gilles": "Unknown",
    "Parme - Clichy": "Unknown",
    "Bosquet - Saint-Dominique": "Unknown",
    "Louis le Grand - Italiens": "Unknown",
    "Sèvres - Général Leclerc": "Unknown",
    "Saint-Denis - Université": "Unknown",
    "Frères Flavien - Porte des Lilas": "Unknown",
    "Saint-Denis - Réaumur": "Unknown",
    "Joffre - Aigle": "Unknown",
    "Française - Etienne Marcel": "Unknown",
    "Nationale - Vincent Auriol": "Unknown",
    "Olivier de Serres - Leriche": "Unknown",
    "Cours de Vincennes - Soult": "Unknown",
    "Cléry - Montmartre": "Unknown",
    "Adolphe Lalyre - Armand Silvestre": "Unknown",
    "Temple - Haudriettes": "Unknown",
    "Bézout - Général Leclerc": "Unknown",
    "Blancs-Manteaux - Archives": "Unknown",
    "Parc Roger Salengro": "Unknown",
    "Montmartre - Etienne Marcel": "Unknown",
    "Square Emile - Chautemps": "Unknown",
    "Hôtel de Ville de Chaville": "Unknown",
    "Didot - Mariniers": "Unknown",
    "Etienne Marcel - Montorgueil": "Unknown",
    "Lally-Tollendal - Armand Carrel": "Unknown",
    "Lagny - Auguste Blanqui": "Unknown",
    "Gardenat-Lapostol - Velettes": "Unknown",
    "Place du 17 Octobre": "Unknown",
    "Adolphe Pinard - Victor Hugo": "Unknown",
    "Kléber - National": "Unknown",
    "Mairie du 3ème": "Unknown",
    "Mairie du 4ème": "Unknown",
    "Fille du Calvaire - Turenne": "Unknown",
    "Cesaria Evora - Rosa Parks": "Unknown",
    "Victoire - Laffitte": "Unknown",
    "Saint-Michel - Luxembourg": "Unknown",
    "Gare d'Austerlitz - Pont Charles de Gaulle": "Unknown",
    "Lisbonne - Monceau": "Unknown",
    "Pierre Sarrazin - Saint-Michel": "Unknown",
    "Eugène Varlin - Place de la Paix": "Unknown",
    "Froidevaux - Boulard": "Unknown",
    "Tiron - Rivoli": "Unknown",
    "Verdier - Jean Jaurès": "Unknown",
    "Alouettes - Maréchal de Lattre de Tassigny": "Unknown",
    "Mairie du Kremlin-Bicêtre": "Unknown",
    "Jean Bleuzen - Square du 11 Novembre": "Unknown",
    "Rivoli - Musée du Louvre": "Unknown",
    "Place de l'Hôtel de Ville": "Unknown",
    "Bas - Gabriel Péri": "Unknown",
    "Séminaire de Conflans - Liberté": "Unknown",
    "Barbès - Monique Maunoury": "Unknown",
    "Hippodrome Paris-Vincennes": "Unknown",
    "Saint-Gilles - Turenne": "Unknown",
    "Gardenat Lapostol - Franklin Roosevelt": "Unknown",
    "Pau Casals - Neuve Tolbiac": "Unknown",
    "Jean-Jacques Rousseau - Deux Ecus": "Unknown",
    "Square Pierre Lazareff": "Unknown",
    "Place Paul Delouvrier": "Unknown",
    "Candale - Mehul": "Unknown",
    "Édouard Vaillant - Place Jean Jaurès": "Unknown",
    "Aboukir - Alexandrie": "Unknown",
    "Saint-Bon - Rivoli": "Unknown",
    "Porte de Saint Cloud - Parc des Princes": "Unknown",
    "Quai Jules Guesde - Saint-Simon": "Unknown",
    "Place de la Bastille - Bourdon": "Unknown",
    "Saint-Jacques - Val de Grâce": "Unknown",
    "Village Saint-Paul": "Unknown",
    "Gare du Nord - La Chapelle": "Unknown",
    "Choiseul - Quatre Septembre": "Unknown",
    "Bastille - Beaumarchais": "Unknown",
    "Waldeck Rochet - Germaine Tillon": "Unknown",
    "Place du 8 mai 1945.": "Unknown",
    "Chaussée d'Antin - Haussmann": "Unknown",
    "Gare des Vallées": "Unknown",
    "Oratoire - Rivoli": "Unknown",
    "Alger - Rivoli": "Unknown",
    "Mairie du 2ème": "Unknown",
    "Place du Lieutenant Henri Karcher": "Unknown",
    "Grande Rue - Europe": "Unknown",
    "Custine - Ramey": "Unknown",
    "Berthier - Porte de Clichy": "Unknown",
    "Ventadour - Opéra": "Unknown",
    "Port - Confluence": "Unknown",
    "Saint-Honoré - 29 juillet": "Unknown",
    "Saint-Amand - Labrouste": "Unknown",
    "Gare de Sèvres - Ville d'Avray": "Unknown",
    "Saint Pères - Saint Germain": "Unknown",
    "Saint-Placide - Cherche Midi": "Unknown",
    "Marx Dormoy - Château Sainte-Barbe": "Unknown",
    "Amédée Huon - Fort d'Ivry": "Unknown",
    "Saint-Honoré - Musée du Louvre": "Unknown",
    "Guy Môquet - Parvis Georges Marchais": "Unknown",
    "Marseillaise - Grenade": "Unknown",
    "Decrès - Alésia": "Unknown",
    "Le Goff - Gay-Lussac": "Unknown",
    "Square Victor Basch": "Unknown",
    "Jouffroy d'Abbans - Villiers": "Unknown",
    "Gare RER - Canadiens": "Unknown",
    "Stade Pershing": "Unknown",
    "Archives - Pastourelle": "Unknown",
    "Résistance - Parmentier": "Unknown",
    "Jean Jaurès - Paul Lafargue": "Unknown",
    "Quai de l'Aisne - Général Leclerc": "Unknown",
    "Arthur Ranc - Hôpital Bichat": "Unknown",
    "Suresnes - Muette à Neuilly": "Unknown",
    "Bréa - Raspail": "Unknown",
    "Verdun - Carnot": "Unknown",
    "Parc Floral du Bel Air": "Unknown",
    "Place de la Division Leclerc": "Unknown",
    "Cardinal Lavigerie": "Unknown",
    "Belfort - Victor Hugo": "Unknown",
    "Belles Feuilles - Place de Mexico": "Unknown",
    "Porte Dauphine": "Unknown",
    "André Theuriet - Blagis": "Unknown",
    "Lampes": "Unknown",
    "Jules Guesdes - Carnot": "Unknown",
    "Victor Hugo - Gare": "Unknown",
    "Place André Malraux": "Unknown",
    "Les Halles - Saint-Eustache": "Unknown",
    "Place des Victoires": "Unknown",
    "Victor Massé - Jean-Baptiste Pigalle": "Unknown",
    "Place de l'Eglise - Vitry-sur-Seine": "Unknown",
    "Coquillière - Louvre": "Unknown",
    "Porte de Pantin.": "Unknown",
    "Saint-Marc - Feydeau": "Unknown",
    "Danielle Casanova - Opéra": "Unknown",
    "Magenta - Chabrol": "Unknown",
    "Vaugirard - Monsieur le Prince": "Unknown",
    "Saint-Mande - Picpus": "Unknown",
    "Les Blagis": "Unknown",
    "Victor Hugo - Paul Eluard": "Unknown",
    "Blanqui - Docteur Bauer": "Unknown",
    "Youri Gagarine - Commune de Paris": "Unknown",
    "Quai de Sèvres - Manufacture Nationale": "Unknown",
    "Silly - Louis Blériot": "Unknown",
    "Paganini - Davout": "Unknown",
    "Stalingrad - Henri Luisette": "Unknown",
    "Gare de Robinson": "Unknown",
    "Sorbier - Gasnier-Guy": "Unknown",
    "Gare RER - Maurice Grandcoing": "Unknown",
    "Dutot - Place Alleray": "Unknown",
    "Jardin Modèle - Pierre Boudou": "Unknown",
    "Bagnolet - Place Saint-Blaise": "Unknown",
    "Strasbourg - Saint-Denis": "Unknown",
    "République - Louis Loucheur": "Unknown",
    "Henri Barbusse - Gabriel Péri": "Unknown",
    "Vincent Auriol - Louise Weiss": "Unknown",
    "André Mazet - Saint-André des Arts": "Unknown",
    "Mairie": "Unknown",
    "Mariotte - Batignolles": "Unknown",
    "Londres - Europe": "Unknown",
    "Stade de France - Francis de Pressensé": "Unknown",
    "Jouffroy d'Abbans - Malesherbes": "Unknown",
    "Charenton - Wattignies": "Unknown",
    "Béranger - Félix Faure": "Unknown",
    "Pierre Charron - Champs-Elysées": "Unknown",
    "Bichat - Grange aux Belles": "Unknown",
    "Stéphanie Bouvard - Gambetta": "Unknown",
    "Saint-Augustin": "Unknown",
    "Mûriers - Père Lachaise": "Unknown",
    "Riquet - Marx Dormoy": "Unknown",
    "Chastenet de Géry - Marcel Paul": "Unknown",
    "Martyrs de Châteaubriant - Jean Grandel": "Unknown",
    "Ney - Porte de Montmartre": "Unknown",
    "Place Charles de Gaulle": "Unknown",
    "Clef des Champs - Albert Dhalenne": "Unknown",
    "Gare - Aristide Briand": "Unknown",
    "Place du Maréchal de Lattre de Tassigny": "Unknown",
    "Belleville -  Pré Saint-Gervais": "Unknown",
    "Chevaleret - Louise Weiss": "Unknown",
    "Bons Raisins - Voltaire": "Unknown",
    "Manin - Secrétan": "Unknown",
    "Château de Vincennes": "Unknown",
    "Place Denfert-Rochereau": "Unknown",
    "Bobillot - Tolbiac": "Unknown",
    "Général Leclerc - Bièvre": "Unknown",
    "Edith Cavell - Volta": "Unknown",
    "Mairie de Rosny-sous-Bois": "Unknown",
    "Danielle Casanova - Ledru-Rollin": "Unknown",
    "Gobelins - Port-Royal": "Unknown",
    "Porte de Versailles": "Unknown",
    "Place du Docteur Yersin": "Unknown",
    "Léon Frot - Charonne": "Unknown",
    "Maxime Gorki - Paul Vaillant-Couturier": "Unknown",
    "Cambronne - Mademoiselle": "Unknown",
    "Francoeur - Caulaincourt": "Unknown",
    "Euryale Dehaynin - Loire": "Unknown",
    "Lecourbe - Convention": "Unknown",
    "Dôme - République": "Unknown",
    "Pyrénées - Cours de Vincennes": "Unknown",
    "Franquet - Labrouste": "Unknown",
    "Hauteville - Bonne Nouvelle": "Unknown",
    "Roquette - Auguste Laurent": "Unknown",
    "Place de la vache noire": "Unknown",
    "Place Charles Digeon": "Unknown",
    "Gouthière - Poterne des Peupliers": "Unknown",
    "Félix Faure - Convention": "Unknown",
    "Buzenval - Vignoles": "Unknown",
    "Port Royal - Hôpital Cochin": "Unknown",
    "Gergovie - Alésia": "Unknown",
    "Place Eustache Deschamps": "Unknown",
    "LCL Campus - Place Oscar Niemeyer": "Unknown",
    "Général De Gaulle - Vivien": "Unknown",
    "Moscou - Edouard Vaillant": "Unknown",
    "Guillaume Tell - Parc Henri Barbusse": "Unknown",
    "Pyrénées - Charles Renouvier": "Unknown",
    "Hector Malot - Daumesnil": "Unknown",
    "Bercy - Traversiére": "Unknown",
    "Pierre Joseph Desault": "Unknown",
    "Suffren - La Motte-Piquet": "Unknown",
    "Dom-Pérignon - Gravelle": "Unknown",
    "Mairie du 10ème": "Unknown",
    "Duméril - Jeanne d'Arc": "Unknown",
    "Sydney Bechet - Jacques Gautier": "Unknown",
    "Hôtel de Ville de Vincennes": "Unknown",
    "Dominique Pado - Croix Nivert": "Unknown",
    "Jean de la Fontaine - Boulainvilliers": "Unknown",
    "Olympiades": "Unknown",
    "Montreuil - République": "Unknown",
    "Tombe Issoire - René Coty": "Unknown",
    "Pereire - Saussure": "Unknown",
    "Siam - La Pompe": "Unknown",
    "Marcadet - Ramey": "Unknown",
    "George Sand - Jean de La Fontaine": "Unknown",
    "Alexandre Dumas - Place de la Réunion": "Unknown",
    "Saint-Séverin - Saint-Michel": "Unknown",
    "Porte de la Plaine": "Unknown",
    "Marcel Pourtout - Édouard Manet ": "Unknown",
    "Sahel - Général Michel Bizot": "Unknown",
    "Duhamel - André Gide": "Unknown",
    "Ancienne Mairie - André Morizet": "Unknown",
    "Lavoisier - Missak Manouchian": "Unknown",
    "Place Aristide Briand": "Unknown",
    "Général Leclerc - République": "Unknown",
    "Legendre - Nollet": "Unknown",
    "Mairie de Bagnolet": "Unknown",
    "Pierre Brossolette - 12 Février 1934": "Unknown",
    "Square des Amandiers": "Unknown",
    "Charonne - Alexandre Dumas": "Unknown",
    "Maine - Jean Zay": "Unknown",
    "Jean Jaurès - Place de la Libération": "Unknown",
    "Marceau - Président Wilson": "Unknown",
    "Gambetta - Tourelles": "Unknown",
    "René Coty - Place Denfert-Rochereau": "Unknown",
    "Rome - Provence": "Unknown",
    "Gabriel Péri - Place de la Libération": "Unknown",
    "Guy Môquet - Compoint": "Unknown",
    "Championnet.": "Unknown",
    "Quatre Vents - Carrefour de l'Odéon": "Unknown",
    "Reynaldo Hahn - Lagny": "Unknown",
    "Verdier - République": "Unknown",
    "Philippe-Auguste": "Unknown",
    "Bois de Vincennes - Polygone": "Unknown",
    "Colonel Pierre Avia": "Unknown",
    "Marché d'Auteuil": "Unknown",
    "Arthur Auger - Jean Jaurès": "Unknown",
    "Passy - Place du Costa Rica": "Unknown",
    "Jean-Baptiste Charcot - Sainte-Geneviève": "Unknown",
    "Regard - Rennes": "Unknown",
    "Pasteur - Cotentin": "Unknown",
    "Ménilmontant - Oberkampf": "Unknown",
    "Lorraine - Jean Jaurès": "Unknown",
    "Volontaires - Vaugirard": "Unknown",
    "Guillaume Bertrand - République": "Unknown",
    "M.- A. Lagroua Weill-Hallé -  F. Dolto": "Unknown",
    "Victor Hugo - Bineau": "Unknown",
    "Fief - République": "Unknown",
    "Hôtel de Ville de Rueil-Malmaison": "Unknown",
    "Arsonval - Falguière": "Unknown",
    "Montparnasse -  Square Ozanam": "Unknown",
    "Jean Bologne - Passy": "Unknown",
    "Pyrénées - Dagorno": "Unknown",
    "Crimée - Ourcq": "Unknown",
    "Dantzig - Lefebvre": "Unknown",
    "Bobillot - Moulin des Prés": "Unknown",
    "Porte de Charenton": "Unknown",
    "Mairie du 20ème": "Unknown",
    "Place Saint-André des Arts": "Unknown",
    "Rond-Point Rhin et Danube": "Unknown",
    "Flandre - Ourcq": "Unknown",
    "Point du Jour - Jean Jaurès": "Unknown",
    "Geoffroy-Saint-Hilaire - Saint-Marcel": "Unknown",
    "Saint-Maur - République": "Unknown",
    "Metz - Marne": "Unknown",
    "Bertrand Sincholle - Henri Barbusse": "Unknown",
    "Commandant Charcot - Bretteville": "Unknown",
    "Général Michel Bizot - Claude Decaen": "Unknown",
    "Ivry - Baudricourt": "Unknown",
    "Lacépède - Linné": "Unknown",
    "Saint-Mandé - Docteur Arnold Netter": "Unknown",
    "Jacquier - Didot": "Unknown",
    "Guynemer - Jardin du Luxembourg": "Unknown",
    "Verdun - Pierre et Marie Curie": "Unknown",
    "Paul Valery - Victor Hugo": "Unknown",
    "Etienne Dolet - Place Maurice Chevalier": "Unknown",
    "Convention - Campus de Bobigny": "Unknown",
    "Batignolles - Abel Truchet": "Unknown",
    "Saint-Marcel - Hôpital": "Unknown",
    "Alfred de Vigny - Place du Général Brocard": "Unknown",
    "Perrault - Place du Louvre": "Unknown",
    "Fontaine du Tertre - Calvaire": "Unknown",
    "Résistance - Romain Rolland": "Unknown",
    "Place Tristan Bernard": "Unknown",
    "Temple - Jean-Pierre Timbaud": "Unknown",
    "Place d'Italie - Soeur Rosalie": "Unknown",
    "Temple - Charlot": "Unknown",
    "Marcel Monge - Marcel Dassault": "Unknown",
    "Sèvres - Maréchal Juin": "Unknown",
    "Claude Debussy - Marc Bloch": "Unknown",
    "Place Jean Mermoz": "Unknown",
    "Charles de Gaulle - Rue de l'Alma": "Unknown",
    "Place des Arts - Jean Mermoz": "Unknown",
    "Jean Mermoz - Champs-Elysées": "Unknown",
    "Paul Doumer - Stalingrad": "Unknown",
    "Louis Armand - Bernard Palissy": "Unknown",
    "Ménilmontant - Père Lachaise": "Unknown",
    "Hippodrome de Longchamp": "Unknown",
    "Payenne - Square George Caïn": "Unknown",
    "Pyrénées - Ménilmontant": "Unknown",
    "Pavé des Gardes - Charles Vaillant": "Unknown",
    "Georges Pompidou - Verdun": "Unknown",
    "Félix Faure - Lourmel": "Unknown",
    "Gambetta - Saint Fargeau": "Unknown",
    "Macdonald - Césaria Evora": "Unknown",
    "Gare RER - Général de Gaulle": "Unknown",
    "Chevaleret - Tolbiac": "Unknown",
    "Saint-Lazare - Place d'Estienne d'Orves": "Unknown",
    "Epi d'Or - Chevilly": "Unknown",
    "Nungesser - Santé": "Unknown",
    "Dora Maar - Nadia Guendouz": "Unknown",
    "Port - Maurice Chevalier": "Unknown",
    "Gare du Nord - Faubourg Saint-Denis": "Unknown",
    "Galilée - Vernet": "Unknown",
    "Musée d'Orsay": "Unknown",
    "Ménil - Argenteuil": "Unknown",
    "Stalingrad - Barbara": "Unknown",
    "Verdun - Henri Barbusse": "Unknown",
    "Stalingrad - Général de Gaulle": "Unknown",
    "Cartier Bresson - Denis Papin": "Unknown",
    "Pierre Ginier - Clichy": "Unknown",
    "Abbé Carton - Plantes": "Unknown",
    "Carpeaux - Place Jacques Froment": "Unknown",
    "Jemmapes - Ecluses Saint-Martin": "Unknown",
    "Saint-Germain - Verdun": "Unknown",
    "Jean Jaurès - Place du Dr Roux": "Unknown",
    "Val-Fleury": "Unknown",
    "Châteaudun - Place de la Liberté": "Unknown",
    "Faubourg St-Antoine - Place de la Nation": "Unknown",
    "Place Henri Dunant - Gare RER": "Unknown",
    "Gare de Lyon - Roland Barthes": "Unknown",
    "Parc des Pierrettes": "Unknown",
    "Guy Môquet - Jean Moulin": "Unknown",
    "Avenir": "Unknown",
    "Maréchal Leclerc de Hauteclocque - Marché Buzenval": "Unknown",
    "Champs de Manoeuvre - Cartoucherie": "Unknown",
    "Bastille - Biscornet": "Unknown",
    "Charles de Gaulle - Les Sablons": "Unknown",
    "Président Roosevelt - Rouget de Lisle": "Unknown",
    "Richard Lenoir - Place de la Bastille": "Unknown",
    "Jean Bouin - Gouverneur Général Eboué": "Unknown",
    "Division Leclerc - Kléber": "Unknown",
    "Gare Saint-Lazare - Place de Budapest": "Unknown",
    "Hélène et François Missoffe - Emile Borel": "Unknown",
    "Adrien Lesesne - Docteur Bauer": "Unknown",
    "Porte de Clichy - Place des Nations Unies": "Unknown",
    "Henri Barbusse - Bourguignons": "Unknown",
    "Marceau Delorme - Pierre Brossolette": "Unknown",
    "Garibaldi - Gabriel Péri": "Unknown",
    "Bateliers - Quai de Seine": "Unknown",
    "Roland Garros - Jean Bouin": "Unknown",
    "Gare RER": "Unknown",
    "Place de la Paix - Abbé Saint-Pierre": "Unknown",
    "Simone Signoret - Paris": "Unknown",
    "Pontoise - La Tournelle": "Unknown",
    "Gare de l'Est - Chateau Landon": "Unknown",
    "Jonquière - Docteur Paul Brousse": "Unknown",
    "Ordener - Poissonniers": "Unknown",
    "Ruisseau - Ordener": "Unknown",
    "Clignancourt - Ordener": "Unknown",
    "Lauriston - Copernic": "Unknown",
    "Joseph Sansboeuf - Saint Lazare": "Unknown",
    "Choisy - Pointe d'Ivry": "Unknown",
    "Gabriel Péri - Jules Ferry": "Unknown",
    "Place De Fontenoy - Saxe": "Unknown",
    "Suzanne Masson": "Unknown",
    "Volontaires - Lecourbe": "Unknown",
    "Tolbiac - Boussingault": "Unknown",
    "Choisy - Tolbiac": "Unknown",
    "Convention - Lourmel": "Unknown",
    "Granges aux Belles - Hôpital Saint-Louis": "Unknown",
    "Ney - Porte de Clignancourt": "Unknown",
    "Square de Choisy - Eastman": "Unknown",
    "Liberté - Vert-de-Maisons": "Unknown",
    "Place Farhat Hached": "Unknown",
    "Halle Freyssinet - Parvis Alan Turing": "Unknown",
    "Pont de Suresnes": "Unknown",
    "François 1er - Montaigne": "Unknown",
    "Rampal - Belleville": "Unknown",
    "Saint-Jacques - Soufflot": "Unknown",
    "Albert Kahn - Duhesme": "Unknown",
    "Place Pigalle": "Unknown",
    "Faubourg Du Temple - Republique": "Unknown",
    "Rochechouart - Martyrs": "Unknown",
    "Fabre d'Eglantine - Place de la Nation": "Unknown",
    "Jean Jaurès - Presles": "Unknown",
    "Belfort - Voltaire": "Unknown",
    "Alexandre Dumas - Voltaire": "Unknown",
    "Clichy - Douai": "Unknown",
    "Hoche - Tilsitt": "Unknown",
    "Traktir - Foch": "Unknown",
    "Vanne - Général de Gaulle": "Unknown",
    "Place de la République - Temple": "Unknown",
    "Place de la Nation - Taillebourg": "Unknown",
    "Place de la République - Voltaire": "Unknown",
    "Boulets - Voltaire": "Unknown",
    "Jean Jaurès - Ouvrières Pivéreuses": "Unknown",
    "Place de la Montagne du Goulet": "Unknown",
    "Richard Lenoir - Voltaire": "Unknown",
    "Ecole Militaire - Place Joffre": "Unknown",
    "Montreuil - Voltaire": "Unknown",
    "Fédération - Suffren": "Unknown",
    "Mauroy - Cheminots": "Unknown",
    "Colisée - Champs-Elysées": "Unknown",
    "Bourdonnais - Tour Eiffel": "Unknown",
    "Taitbout - Châteaudun": "Unknown",
    "Place Joffre - Frédéric le Play": "Unknown",
    "Solidays": "Unknown",
    "Octave Gréard - Tour Eiffel": "Unknown",
    "Quai de Béthune - Pont de la Tournelle": "Unknown",
    "Diderot - Pierre Bourdan": "Unknown",
    "Préfecture de Créteil": "Unknown",
    "Haut du Mont-Mesly": "Unknown",
    "Stade de la Habette": "Unknown",
    "Hôtel de Ville de Créteil": "Unknown",
    "Créteil Pointe du Lac": "Unknown",
    "Bineau - Louise Michel": "Unknown",
    "Raymond Poincaré - Place Victor Hugo": "Unknown",
    "Dugommier": "Unknown",
    "Hôtel de Ville d'Asnières sur Seine": "Unknown",
    "Centre Hospitalier Intercommunal de Créteil": "Unknown",
    "Créteil Village": "Unknown",
    "Gare de Chaville Rive Gauche": "Unknown",
    "Créteil Pompadour": "Unknown",
    "Place de la Porte de Châtillon": "Unknown",
    "Bobillot - Paulin Mery": "Unknown",
    "Iles de Loisirs de Créteil": "Unknown",
    "Yves Farges - Route d'Enghien": "Unknown",
    "Louis Blanc - Aqueduc": "Unknown",
    "Wilson - Landy": "Unknown",
    "Borrégo - Gambetta": "Unknown",
    "Charles de Gaulle - Jean Lolive": "Unknown",
    "Noisy le Sec - Jean-Baptiste Clément": "Unknown",
    "Gare de la Garenne-Colombes": "Unknown",
    "Alibert - Jemmapes": "Unknown",
    "Cauchy - Cévennes": "Unknown",
    "Bir Hakeim": "Unknown",
    "Danielle Casanova - Place Vendôme": "Unknown",
    "Bois de Vincennes - Gare": "Unknown",
    "Pailleron - Bouret": "Unknown",
    "Michelet - Dr Bauer": "Unknown",
    "Jean Jaurès - Gare de Clamart": "Unknown",
    "Mstislav Rostropovitch - Berthier": "Unknown",
    "Institut de France": "Unknown",
    "Victoria - Place du Chatelet": "Unknown",
    "Grande Armée - Brunel": "Unknown",
    "Saint-Antoine Sévigné": "Unknown",
    "Proudhon - Président Wilson": "Unknown",
    "BNF - Bibliothèque Nationale de France": "Unknown",
    "Balzac - Champs Elysées": "Unknown",
    "Cité de la Musique": "Unknown",
    "Bleuets - Bordières": "Unknown",
    "Saint-Denis - Rivoli": "Unknown",
    "Daumesnil - Picpus": "Unknown",
    "Aristide Briand - Place de la Résistance": "Unknown",
    "Carrefour Pleyel": "Unknown",
    "Place Charles Vallin": "Unknown",
    "Place du Moulin de Javel": "Unknown",
    "Sebastopol - Rambuteau": "Unknown",
    "Léon - Doudeauville": "Unknown",
    "Madeleine Vionnet": "Unknown",
    "Westermeyer - Paul Vaillant-Couturier": "Unknown",
    "Enfants du Paradis - Peupliers": "Unknown",
    "Caumartin - Provence": "Unknown",
    "Clichy - Place Blanche": "Unknown",
    "Tremblay - Lac des Minimes": "Unknown",
    "Gare Saint-Lazare - Cour du Havre": "Unknown",
    "Arbalète - Claude Bernard": "Unknown",
    "Bercy - Villot": "Unknown",
    "Place Balard": "Unknown",
    "Malesherbes - Place de la Madeleine": "Unknown",
}
